"""empty message

Revision ID: 0e4ac908994c
Revises: e0be1bbe564d
Create Date: 2016-08-24 11:34:31.821270

"""

# revision identifiers, used by Alembic.
revision = '0e4ac908994c'
down_revision = 'e0be1bbe564d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'email')
    ### end Alembic commands ###
