"""empty message

Revision ID: 56faffd1c7a5
Revises: afcc282b32c6
Create Date: 2016-08-24 19:31:11.335350

"""

# revision identifiers, used by Alembic.
revision = '56faffd1c7a5'
down_revision = 'afcc282b32c6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('about_me', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('location', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('name', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    op.drop_column('users', 'location')
    op.drop_column('users', 'about_me')
    ### end Alembic commands ###
