"""empty message

Revision ID: a4e7b3eb8200
Revises: afcc282b32c6
Create Date: 2016-08-24 19:27:10.876936

"""

# revision identifiers, used by Alembic.
revision = 'a4e7b3eb8200'
down_revision = 'afcc282b32c6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('about_me', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('location', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('name', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    op.drop_column('users', 'location')
    op.drop_column('users', 'about_me')
    ### end Alembic commands ###
