"""empty message

Revision ID: e0be1bbe564d
Revises: 06019ff4b8c1
Create Date: 2016-08-24 11:28:21.081304

"""

# revision identifiers, used by Alembic.
revision = 'e0be1bbe564d'
down_revision = '06019ff4b8c1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    ### end Alembic commands ###
